version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
exclude_patterns:
 - "templates/*"
 - "logs/*"
 - "static/*"
 - "/tests/*"
 - "*/migrations/*"
 - "/locale/*"