# Generated by Django 3.2 on 2021-05-23 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statuses', '0001_initial'),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of task')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='labels.labels')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='statuses.statuses')),
            ],
        ),
    ]
