# Generated by Django 3.2 on 2021-05-30 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
        ('labels', '0001_initial'),
        ('statuses', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of task')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customuser')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor', to='user.customuser')),
                ('labels', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels', to='labels.labels')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='description', to='statuses.statuses')),
            ],
        ),
    ]
