# Generated by Django 3.2 on 2021-05-31 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0003_alter_tasks_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='labels',
        ),
        migrations.AddField(
            model_name='tasks',
            name='labels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='labels.labels'),
        ),
    ]
