# Generated by Django 3.2 on 2021-05-23 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0003_remove_tasks_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='labels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels', to='labels.labels'),
        ),
    ]
