# Generated by Django 3.2.5 on 2021-08-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
