# Generated by Django 3.2 on 2021-05-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210511_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='date_joined',
            field=models.DateField(auto_now=True),
        ),
    ]
