# Generated by Django 3.2 on 2021-05-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20210511_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_joined',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='name of task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='label',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name of label'),
        ),
        migrations.AlterField(
            model_name='status',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name of status'),
        ),
    ]
