# Generated by Django 3.2 on 2021-05-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20210511_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
